- name: Install vlc ON Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
       update_cache: yes
      when: ansible_distribution in "Ubuntu"

    - name: Install VLC
      apt:
       name: vlc
       state: present
      when: ansible_distribution in "Ubuntu"

