---

- hosts: all
  become: yes
  tasks:

   - name: install apache2 package
     apt:
      name: apache2
      state: present
      update_cache: yes

   - name: add php support for apache 
     apt:
      name: libapache2-mod-php
